# Site settings
# title: Hassan Hafez personal website
email: Hassan1hafez@gmail.com
description: Hassan hafez's personal portfolio and blog.
url: "https://hassanhafezzz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/hassanhafez" # the subpath of your site, e.g. /blog
twitter_username: hassanhafezz
github_username:  hassanhafezzz
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: /blog/:title


theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
